### ISSUE TITLE
Why Cuda Removal?

### ISSUE THREAD

**Issue by IronBeardKnight** [imagegenius/docker-immich#179] opened 2023-09-21 04:19 UTC
Why would you get rid of cuda as its much better than using your cpu for machine learning.

Your Updates
29.07.23: - remove cuda acceleration for machine-learning
23.05.23: - move to ubuntu lunar and support cuda acceleration for machine-learning

**Comment by martabal** [comment] 2023-09-21 07:01
Duplicate of #151

**Closed** 2023-09-21 07:01 UTC
