### ISSUE TITLE
heic thumbnail generation is broken with 1.79

### ISSUE THREAD

**Issue by gnojus** [imagegenius/docker-immich#185] opened 2023-09-29 11:46 UTC
Immich no longer generates heic thumbnails. Wasn't sure if this is immich, or docker-immich issue,
but opened it here since noticed old fixed issue about heic.

logs report `heif: Unsupported feature: Unsupported codec (4.3000)` and `HEIC: bad seek to <number>`
not sure about the exact regression version, but `noml-v1.78.1-ig139` is fine and `noml-v1.79.1-ig142` is broken.

Might be related to https://github.com/immich-app/immich/commit/9030b1f89f1a241cf1d04c95cf343f1d289f1040

**Comment by martabal** [comment] 2023-09-29 13:54
I tried this myself with a HEIC image and cannot reproduce the problem. Can you share a problematic image for troubleshooting?

**Comment by gnojus** [comment] 2023-09-29 13:59
[IMG_2098.heic.gz](https://github.com/imagegenius/docker-immich/files/12766303/IMG_2098.heic.gz)

Although I can't regenerate thumbnails for old images either.
I assume you tried with the `noml` version?

**Comment by martabal** [comment] 2023-09-29 14:17
Oh sorry, I didn't notice you are using the noml version. Indeed, I can reproduce this issue and it's probably because of this commit

**Comment by gnojus** [comment] 2023-10-18 16:00
This is solved by using vips 8.14.5 (can installed from edge repo).
I myself changed to install all packages from alpine edge.

Do you want me to send a PR?

**Comment by martabal** [comment] 2023-10-18 17:35
Thanks for the info, but 8.14.5 is a pre-release, it's not officially out. I think the best thing to do is to wait.

**Comment by martabal** [comment] 2023-10-18 17:45
Well, since alpine has not updated vips since 2 months, there's two possibilities : update the vips package using the edge repo or wait alpine 3.19 (should be released in November or December).

What do you think @hydazz ?

**Comment by hydazz** [comment] 2023-10-19 07:48
a simple `apk add -X http://dl-cdn.alpinelinux.org/alpine/edge/main vips` should suffice for now

**Comment by hydazz** [comment] 2023-11-02 03:03
@gnojus resolved?

**Comment by gnojus** [comment] 2023-11-02 17:22
Yes, thanks.

Not sure if I should close this issue, in case you want to switch back to non-edge packages when alpine creates newer release of vips.

**Closed** 2023-11-03 10:36 UTC
